### ISSUE TITLE
请问下 使用的flutter 的版本是多少呀

### ISSUE THREAD

**Issue by jokunhe** [yechaoa/wanandroid_flutter#10]
大佬你好，目前我本地的sdk版本是1.22.2跑的时候 挺多的版本导致的方法弃用呢。。。
能否告知下您这个项目当时的版本呀

**Comment by yechaoa** [comment]
1.7.8的，可以先根据更新日志改一下先

**Comment by jiashaoying** [comment]
版本太低了，现在Flutter已经3.0了。起码也要适配到Flutter 2.10吧

**Comment by yechaoa** [comment]
Flutter版本已更新至3.7.9
