### ISSUE TITLE
provide

### ISSUE THREAD

**Issue by wzg-githome** [yechaoa/wanandroid_flutter#12]
provide-1.0.2/lib/**provide**.dart:570:28: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.

**Comment by wzg-githome** [comment]
> provide-1.0.2/lib/ **provide** .dart:570:28: 错误：未为类“BuildContext”定义方法“inheritFromWidgetOfExactType”。

It's done. I'm a beginner

**Comment by wzg-githome** [comment]
后来我修复了上面的问题后，出现了这个问题，作者帮我看看？

======== Exception caught by widgets library =======================================================
### **The following NoSuchMethodError was thrown building Provide<ThemeProvide>(dirty):
The method 'getValue' was called on null.
Receiver: null
Tried calling: getValue<ThemeProvide>(scope: null)**

The relevant error-causing widget was: 
  Provide<ThemeProvide> file:///D:/ChromeCoreDownloads/a_flutter/wanandroid_flutter-master/lib/main.dart:58:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Provide.build (package:provide/provide.dart:274:54)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4648:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
...

**Comment by 764990722** [comment]
我也遇到了：The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'
请问provide异常解决了吗？

**Comment by yechaoa** [comment]
provide已迁移至provider，可以重新编译看看
