### ISSUE TITLE
dio版本必须在2.1.3？升级以后不能运行

### ISSUE THREAD

**Issue by Mecil9** [yechaoa/wanandroid_flutter#4]
Compiler message:
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,

**Comment by yechaoa** [comment]
是的，3.0+是不兼容升级，现已调整提交
