### ISSUE TITLE
关于entity的请教

### ISSUE THREAD

**Issue by 812781385** [yechaoa/wanandroid_flutter#6]
您好作者，请问一下我这样的数据改怎么写这个entity啊？
{"data":{"vehicles":[{"password":"123123","plate_num":"沪A00000","vehicle_model":"gm","vin":"v2"}]},"message":"Operation successful","resultcode":0}

**Comment by yechaoa** [comment]
手写太费劲了,建议用FlutterJsonBeanFactory插件

**Comment by 812781385** [comment]
您好，我用FlutterJsonBeanFactory插件生成的文件是这样的，我该如何使用呢？
我这样写的话他说没有jsonfrom方法,error: The method 'fromJson' isn't defined for the type 'SearchEntity'. :
var response = await HttpUtil().post(Api.SEARCH, data: data, context: context);
Map searchMap = json.decode(response.toString());
var searchEntity = SearchEntity.fromJson(searchMap);

------------search_entiry.dart-----------------
import 'package:wds/generated/json/base/json_convert_content.dart';

class SearchEntity with JsonConvert<SearchEntity> {
	SearchData data;
	String message;
	int resultcode;
}

class SearchData with JsonConvert<SearchData> {
	List<dynamic> authorizedlist;
	List<String> failurelist;
	List<dynamic> unauthorizedlist;
}

**Comment by yechaoa** [comment]
你这是没有fromJson方法啊,可能生成的姿势不对...

**Comment by 812781385** [comment]
对啊，我安装完FlutterJsonBeanFactory插件。在android studio里点击new，看到的是”JsonToDartBeanAction",而不是“dart bean class file from json”。是怎么回事呀？

**Comment by yechaoa** [comment]
是插件更新了。。。https://github.com/zhangruiyu/FlutterJsonBeanFactory
