### ISSUE TITLE
一直提示库文件引入错误

### ISSUE THREAD

**Issue by CodeDome** [yechaoa/wanandroid_flutter#7]
一直提示库文件引入错误
![截屏2020-10-22 下午7 44 42](https://user-images.githubusercontent.com/16448830/96867347-2c44e400-149f-11eb-99a9-aeaf5d2d6066.png)
改成绝对路径也不行

**Comment by CodeDome** [comment]
PhoenixHeader，PhoenixFooter这两个组建引入错误

**Comment by yechaoa** [comment]
重新packages get试下，或者重新拉下项目，或者没有镜像的话加下镜像试试

**Comment by zyzTm** [comment]
我也碰到了同样的问题，后来我把
// import 'package:wanandroid_flutter/widget/my_taurus_footer.dart';
// import 'package:wanandroid_flutter/widget/my_taurus_header.dart';
注释掉了就能使用了。

**Comment by yechaoa** [comment]
项目已更新，可重新试试
