### ISSUE TITLE
下载玩安卓app没有数据，是不是接口出问题了

### ISSUE THREAD

**Issue by Turing-bei** [yechaoa/wanandroid_flutter#9]
请大佬检查一下，什么情况。还有大佬有学习群吗？

**Comment by yechaoa** [comment]
我这边运行正常啊。。暂时没有群。

**Comment by Turing-bei** [comment]
不对呀，我这边下载安装完没有数据。

**Comment by Turing-bei** [comment]
> 我这边运行正常啊。。暂时没有群。

大佬，你下载你GitHub上的安装包试试，我这边安装的是没有数据。

**Comment by yechaoa** [comment]
要不先编译运行，我有空看看什么问题

**Comment by akita1987** [comment]
我也是下载安装后没有数据

**Comment by skrlis** [comment]
NoSuchMethodError: The method '[]' was called on null.报错

**Comment by yechaoa** [comment]
版本已更新，可编译最新版本运行尝试
